# Generated by Django 6.0 on 2026-01-02 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
        ('users', '0003_alter_user_referral_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='referraltransaction',
            unique_together={('referrer', 'referred_user')},
        ),
        migrations.DeleteModel(
            name='ReferralCode',
        ),
    ]
