# Generated by Django 6.0 on 2026-01-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='daraja_conversation_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='originator_conversation_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
