# Generated by Django 6.0 on 2026-01-07 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0002_withdrawalrequest_linked_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='linked_transaction',
        ),
    ]
