# Generated by Django 5.2.10 on 2026-04-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('withdrawals', '0003_systemsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='withdrawalrequest',
            name='linked_transaction',
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='processed_callbacks',
            field=models.JSONField(blank=True, default=list, help_text='List of OriginatorConversationID or ConversationID already processed'),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='reference_code',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('needs_review', 'Needs Review')], default='pending', max_length=20),
        ),
    ]
