# Generated by Django 6.0 on 2026-01-08 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_alter_wallettransaction_status'),
        ('withdrawals', '0003_remove_withdrawalrequest_linked_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='linked_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_request', to='wallets.wallettransaction'),
        ),
    ]
