# Generated by Django 5.2.10 on 2026-04-29 00:11

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('elite', 'Elite')], max_length=20, unique=True)),
                ('price_kes', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('trial_days', models.PositiveIntegerField(default=0)),
                ('tier_level', models.PositiveSmallIntegerField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of feature descriptions')),
                ('is_active', models.BooleanField(default=True, help_text='Hide plan from selection if False')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['tier_level'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=50)),
                ('checkout_request_id', models.CharField(max_length=100, unique=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Daraja error description if failed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription Transaction',
                'verbose_name_plural': 'Subscription Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('pdf_file', models.FileField(help_text='Password-protected PDF receipt', upload_to='receipts/subscriptions/%Y/%m/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('downloaded_count', models.PositiveIntegerField(default=0)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='subscriptions.subscriptiontransaction')),
            ],
            options={
                'verbose_name': 'Subscription Receipt',
                'verbose_name_plural': 'Subscription Receipts',
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('grace_end_date', models.DateTimeField(blank=True, null=True)),
                ('is_trial', models.BooleanField(default=False)),
                ('auto_renew', models.BooleanField(default=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_subscriptions', to='subscriptions.subscriptionplan')),
                ('upgraded_from', models.ForeignKey(blank=True, help_text='Previous subscription if this is an upgrade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgraded_to', to='subscriptions.usersubscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='subscriptions.usersubscription'),
        ),
        migrations.CreateModel(
            name='SubscriptionEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('expiry_reminder_3day', '3-Day Expiry Reminder'), ('grace_period_warning', 'Grace Period Warning'), ('expired_notice', 'Expired Notice'), ('trial_ending', 'Trial Ending Soon'), ('upgrade_offer', 'Upgrade Opportunity')], max_length=30)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False, help_text='Confirmed by email backend')),
                ('error_message', models.TextField(blank=True)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='subscriptions.usersubscription')),
            ],
            options={
                'verbose_name': 'Subscription Email Log',
                'verbose_name_plural': 'Subscription Email Logs',
            },
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'status'], name='subscriptio_user_id_28ce5e_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['end_date', 'status'], name='subscriptio_end_dat_58cd8a_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['grace_end_date'], name='subscriptio_grace_e_6c24ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='one_active_subscription_per_user'),
        ),
        migrations.AddIndex(
            model_name='subscriptiontransaction',
            index=models.Index(fields=['checkout_request_id'], name='subscriptio_checkou_83115a_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptiontransaction',
            index=models.Index(fields=['user', 'status'], name='subscriptio_user_id_c05d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptiontransaction',
            index=models.Index(fields=['transaction_date'], name='subscriptio_transac_d6ee63_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionemaillog',
            index=models.Index(fields=['subscription', 'email_type'], name='subscriptio_subscri_0d2dd7_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionemaillog',
            index=models.Index(fields=['sent_at'], name='subscriptio_sent_at_dc651b_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionemaillog',
            constraint=models.UniqueConstraint(condition=models.Q(('sent_at__gte', datetime.datetime(2026, 4, 28, 23, 11, 50, 300241, tzinfo=datetime.timezone.utc))), fields=('subscription', 'email_type'), name='no_duplicate_email_within_hour'),
        ),
    ]
