# Generated by Django 5.2.10 on 2026-04-29 12:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptionreceipt',
            name='transaction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='subscriptions.subscriptiontransaction'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_subscriptions', to='subscriptions.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='upgraded_from',
            field=models.ForeignKey(blank=True, help_text='Previous subscription if this is an upgrade', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgraded_to', to='subscriptions.usersubscription'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscriptiontransaction',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='subscriptions.usersubscription'),
        ),
        migrations.AddField(
            model_name='subscriptionemaillog',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='subscriptions.usersubscription'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'status'], name='subscriptio_user_id_28ce5e_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['end_date', 'status'], name='subscriptio_end_dat_58cd8a_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['grace_end_date'], name='subscriptio_grace_e_6c24ab_idx'),
        ),
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('user',), name='one_active_subscription_per_user'),
        ),
        migrations.AddIndex(
            model_name='subscriptiontransaction',
            index=models.Index(fields=['checkout_request_id'], name='subscriptio_checkou_83115a_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptiontransaction',
            index=models.Index(fields=['user', 'status'], name='subscriptio_user_id_c05d5a_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptiontransaction',
            index=models.Index(fields=['transaction_date'], name='subscriptio_transac_d6ee63_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionemaillog',
            index=models.Index(fields=['subscription', 'email_type'], name='subscriptio_subscri_0d2dd7_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptionemaillog',
            index=models.Index(fields=['sent_at'], name='subscriptio_sent_at_dc651b_idx'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionemaillog',
            constraint=models.UniqueConstraint(condition=models.Q(('sent_at__gte', datetime.datetime(2026, 4, 29, 11, 14, 14, 584689, tzinfo=datetime.timezone.utc))), fields=('subscription', 'email_type'), name='no_duplicate_email_within_hour'),
        ),
    ]
