# Generated by Django 5.2.10 on 2026-04-29 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriptionemaillog',
            name='no_duplicate_email_within_hour',
        ),
        migrations.AddConstraint(
            model_name='subscriptionemaillog',
            constraint=models.UniqueConstraint(condition=models.Q(('sent_at__gte', datetime.datetime(2026, 4, 29, 12, 48, 6, 2957, tzinfo=datetime.timezone.utc))), fields=('subscription', 'email_type'), name='no_duplicate_email_within_hour'),
        ),
    ]
