# Generated by Django 5.2.10 on 2026-05-01 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_remove_subscriptionemaillog_no_duplicate_email_within_hour_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriptionemaillog',
            name='no_duplicate_email_within_hour',
        ),
        migrations.AlterField(
            model_name='subscriptionemaillog',
            name='email_type',
            field=models.CharField(choices=[('activation_notice', 'Subscription Activated'), ('cancelled_notice', 'Subscription Cancelled'), ('expired_notice', 'Subscription Expired'), ('expiry_reminder_7day', '7-Day Expiry Reminder'), ('expiry_reminder_3day', '3-Day Expiry Reminder'), ('grace_period_warning', 'Grace Period Warning'), ('trial_ending', 'Trial Ending Soon'), ('upgrade_offer', 'Upgrade Opportunity')], max_length=30),
        ),
        migrations.AlterField(
            model_name='subscriptionreceipt',
            name='pdf_file',
            field=models.FileField(help_text='PDF receipt file', upload_to='receipts/subscriptions/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='grace_end_date',
            field=models.DateTimeField(blank=True, help_text='end_date + 2 days. Access continues in grace period.', null=True),
        ),
    ]
