# Generated by Django 5.2.10 on 2026-05-01 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_remove_subscriptionemaillog_no_duplicate_email_within_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionemaillog',
            name='email_type',
            field=models.CharField(choices=[('expiry_reminder_3day', '3-Day Expiry Reminder'), ('grace_period_warning', 'Grace Period Warning'), ('expired_notice', 'Expired Notice'), ('trial_ending', 'Trial Ending Soon'), ('upgrade_offer', 'Upgrade Opportunity')], max_length=30),
        ),
        migrations.AlterField(
            model_name='subscriptionreceipt',
            name='pdf_file',
            field=models.FileField(help_text='Password-protected PDF receipt', upload_to='receipts/subscriptions/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='grace_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='subscriptionemaillog',
            constraint=models.UniqueConstraint(condition=models.Q(('sent_at__gte', datetime.datetime(2026, 5, 1, 19, 32, 31, 334469, tzinfo=datetime.timezone.utc))), fields=('subscription', 'email_type'), name='no_duplicate_email_within_hour'),
        ),
    ]
