# Generated by Django 5.2.10 on 2026-05-01 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_subscriptionemaillog_email_type_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscriptionemaillog',
            name='no_duplicate_email_within_hour',
        ),
        migrations.AlterField(
            model_name='subscriptionemaillog',
            name='email_type',
            field=models.CharField(choices=[('activation_notice', 'Subscription Activated'), ('cancelled_notice', 'Subscription Cancelled'), ('expiry_reminder_3day', '3-Day Expiry Reminder'), ('grace_period_warning', 'Grace Period Warning'), ('expired_notice', 'Expired Notice'), ('trial_ending', 'Trial Ending Soon'), ('upgrade_offer', 'Upgrade Opportunity')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='subscriptionemaillog',
            constraint=models.UniqueConstraint(condition=models.Q(('sent_at__gte', datetime.datetime(2026, 5, 1, 20, 23, 51, 257510, tzinfo=datetime.timezone.utc))), fields=('subscription', 'email_type'), name='no_duplicate_email_within_hour'),
        ),
    ]
