# Generated by Django 5.2.10 on 2026-04-29 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usersurveysubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who reviewed this submission', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_survey_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usersurveysubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surveyanswer',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.usersurveysubmission'),
        ),
        migrations.AddIndex(
            model_name='usersurveysubmission',
            index=models.Index(fields=['user', 'status'], name='surveys_use_user_id_7c3ae5_idx'),
        ),
        migrations.AddIndex(
            model_name='usersurveysubmission',
            index=models.Index(fields=['category', 'status'], name='surveys_use_categor_f951d5_idx'),
        ),
        migrations.AddIndex(
            model_name='usersurveysubmission',
            index=models.Index(fields=['status', 'submitted_at'], name='surveys_use_status_573394_idx'),
        ),
        migrations.AddConstraint(
            model_name='usersurveysubmission',
            constraint=models.UniqueConstraint(fields=('user', 'category'), name='one_submission_per_user_per_category'),
        ),
        migrations.AddConstraint(
            model_name='surveyanswer',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='one_answer_per_question_per_submission'),
        ),
    ]
