# Generated by Django 6.0 on 2026-01-02 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('firebase_uid', models.CharField(max_length=128, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=15)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('house_number', models.CharField(blank=True, max_length=20)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('town', models.CharField(blank=True, max_length=100)),
                ('skills', models.JSONField(default=list)),
                ('referral_code', models.CharField(blank=True, max_length=8, unique=True)),
                ('payout_method', models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('bank', 'Bank')], max_length=10)),
                ('payout_phone', models.CharField(blank=True, max_length=15)),
                ('payout_bank_name', models.CharField(blank=True, max_length=100)),
                ('payout_bank_branch', models.CharField(blank=True, max_length=100)),
                ('payout_account_number', models.CharField(blank=True, max_length=50)),
                ('is_onboarded', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
            ],
        ),
    ]
