# Generated by Django 5.2.10 on 2026-04-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_device_info_user_last_seen_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_preferences_token',
            field=models.CharField(blank=True, help_text='Secure token for email preference links', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_promotional_emails',
            field=models.BooleanField(default=True, help_text='Receive promotional and update emails'),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_statement_emails',
            field=models.BooleanField(default=True, help_text='Receive account statement emails'),
        ),
        migrations.AddField(
            model_name='user',
            name='receive_task_notifications',
            field=models.BooleanField(default=True, help_text='Receive emails about new task assignments'),
        ),
    ]
