# Generated by Django 6.0 on 2026-01-09 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_type', models.CharField(choices=[('main', 'Main Wallet'), ('referral', 'Referral Wallet')], max_length=10)),
                ('transaction_type', models.CharField(choices=[('task_earning', 'Task Earning'), ('referral_bonus', 'Referral Bonus'), ('activation_payment', 'Activation Payment'), ('withdrawal', 'Withdrawal'), ('admin_adjustment', 'Admin Adjustment')], max_length=20)),
                ('source', models.CharField(choices=[('system', 'System'), ('admin', 'Admin'), ('user', 'User')], default='system', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('running_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('running_balance__gte', 0)), name='non_negative_running_balance')],
            },
        ),
    ]
