# Generated by Django 5.2.10 on 2026-04-29 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
        ('withdrawals', '0004_remove_withdrawalrequest_linked_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransaction',
            name='source',
        ),
        migrations.RemoveField(
            model_name='wallettransaction',
            name='status',
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='linked_withdrawal',
            field=models.ForeignKey(blank=True, help_text='Reference to withdrawal this transaction relates to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='withdrawals.withdrawalrequest'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='running_balance',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('task_earning', 'Task Earning'), ('referral_bonus', 'Referral Bonus'), ('activation_payment', 'Activation Payment'), ('withdrawal', 'Withdrawal'), ('withdrawal_pending', 'Withdrawal Pending'), ('withdrawal_reversal', 'Withdrawal Reversal'), ('admin_adjustment', 'Admin Adjustment')], max_length=25),
        ),
    ]
