# Generated by Django 5.2.10 on 2026-04-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_remove_wallettransaction_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('survey_earning', 'Survey Earning'), ('referral_bonus', 'Referral Bonus'), ('activation_payment', 'Activation Payment'), ('withdrawal', 'Withdrawal'), ('withdrawal_pending', 'Withdrawal Pending'), ('withdrawal_reversal', 'Withdrawal Reversal'), ('admin_adjustment', 'Admin Adjustment')], max_length=25),
        ),
    ]
