# Generated by Django 6.0 on 2026-01-08 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0002_alter_wallettransaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='running_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12),
        ),
    ]
