# Generated by Django 6.0 on 2026-01-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_referral_code'),
        ('wallets', '0003_alter_wallettransaction_running_balance'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='wallettransaction',
            constraint=models.CheckConstraint(condition=models.Q(('running_balance__gte', 0)), name='non_negative_running_balance'),
        ),
    ]
